### PR TITLE
Update __init__.py added support for IP8M type camera like model IP8M-2796E-AI 

### PR DESCRIPTION
**Pull request by alpauna**
Modified the or to add a starts with on the model looking for IP8M  in the model name.

### CODE REVIEW

**Comment by alpauna** [comment]
Tested on my IP8M-2796E-AI camera and it works great.
SecurityLightAdded

**Comment by rroller** [comment]
Thanks!

**Comment by rroller** [comment]
Sorry I had to revert this change. See https://github.com/rroller/dahua/issues/410
Can you try to figure out a safer way to load this

**Comment by alpauna** [comment]
So would it be safer to be more specific on the model IP8M-2796E so
`or self.model.startswith("IP8M-2796E")` 
since it appears to be impacting certain models of IP8M cameras hate to be so specific but I lost some functionality by the rollback.

**Pull request merged**
