### PR TITLE
Use custom SSL context to specify cipher

### PR DESCRIPTION
**Pull request by idekker**
In the original patch I missed that in control_flow.py there is also a client session created that needs patching. Maybe something to refactor to a single utility.

### CODE REVIEW

**Comment by idekker** [comment]
Part 2 of the fix for #203

**Comment by idekker** [comment]
The test failure seems unrelated to my changes, but let me know what I need to do to debug them.

**Review by rroller — APPROVED** [review]

**Comment by rroller** [comment]
THanks!

**Comment by rroller** [comment]
Released in 0.9.45 - https://github.com/rroller/dahua/releases/tag/0.9.45

**Pull request merged**
