### PR TITLE
Fix detecting DHI_NVR as doorbell 

### PR DESCRIPTION
**Pull request by goblinmaks**
Fix detection DHI_NVR as doorbell
#241

### CODE REVIEW

**Comment by goblinmaks** [comment]
@rroller thanks

**Comment by goblinmaks** [comment]
@tomlut yes, it should fix #168 also

**Comment by tomlut** [comment]
One of my 6 cameras (all connect to the same NVR):

Screenshot 2022-12-15 at 14-24-19 Settings – Home Assistant

**Comment by goblinmaks** [comment]
@rroller could you please review this PR.

**Comment by rroller** [comment]
> @rroller could you please review this PR. 

Will try to get to this very soon

**Comment by goblinmaks** [comment]
@rroller any update here ?

**Comment by rroller** [comment]
Thanks for this! Merging!

**Review by rroller — APPROVED** [review]

**Comment by rroller** [comment]
Released in 0.9.45 - https://github.com/rroller/dahua/releases/tag/0.9.45

**Pull request merged**
