### PR TITLE
Add support for Imou DB61i same as Amcrest AD410.

### PR DESCRIPTION
**Pull request by rwalker777**
Added support for the Imou DB61i which is identical to the Amcrest AD410.

### CODE REVIEW

**Review by rroller — APPROVED** [review]

**Comment by rroller** [comment]
Thanks!

**Comment by jrb80** [comment]
@rwalker777 I've been using the DB61i for a few years now with this integration, how does this commit change anything? Fyi, Imou is the consumer part of Dahau, and Dahua manufacture the AM410 for Amcrest (they are just a marketing company/brand).

**Comment by rwalker777** [comment]
This gives doorbell press, ability to turn motion detect on and off and
control of the light.

**Comment by jrb80** [comment]
The doorbell button has always worked with the `binary_sensor.doorbell_alarm_local` entity and it continues to work that way, and yes now a dedicated button entity is created `binary_sensor.doorbell_button_pressed `

This is the result that I get when pressing the button, is this the expected results? The `binary_sensor.doorbell_button_pressed ` state says `Detected sound` and `Clear`. Whilst the  `binary_sensor.doorbell_alarm_local` entity goes between `Safe` and `Unsafe` which remains unchanged. Perhaps the button entity state description is incorrect?

Btw, I appreciate the new functionality ;-)

Button Pressed

Alarm Local

**Comment by rwalker777** [comment]
That is exactly how the AD410 always worked.  Changing it now would be breaking...

**Pull request merged**
